import Foundation

struct L {
    let settings: AppSettings
    
    init(_ settings: AppSettings) {
        self.settings = settings
    }
    
    func s(_ key: String) -> String {
        let dict = settings.language == .russian ? Self.ru : Self.en
        return dict[key] ?? key
    }
    
    // MARK: - English
    static let en: [String: String] = [
        // App
        "app.tagline": "Cargo delivery, simplified",
        
        // Auth
        "auth.email": "Email",
        "auth.password": "Password",
        "auth.login": "Log In",
        "auth.signup": "Sign Up",
        "auth.noAccount": "Don't have an account? Sign up",
        "auth.invalidCredentials": "Invalid email or password",
        "auth.fillAllFields": "Please fill in all fields",
        "auth.emailExists": "An account with this email already exists",
        "auth.createAccount": "Create Account",
        "auth.personalInfo": "Personal Info",
        "auth.fullName": "Full Name",
        "auth.phone": "Phone",
        "auth.iAmA": "I am a",
        "auth.role": "Role",
        
        // Tabs
        "tab.myOrders": "My Orders",
        "tab.newOrder": "New Order",
        "tab.profile": "Profile",
        "tab.available": "Available",
        "tab.myJobs": "My Jobs",
        "tab.users": "Users",
        "tab.orders": "Orders",
        
        // Orders
        "order.route": "Route",
        "order.from": "From",
        "order.to": "To",
        "order.fromCity": "From (city)",
        "order.toCity": "To (city)",
        "order.cargoDetails": "Cargo Details",
        "order.type": "Type",
        "order.weight": "Weight (kg)",
        "order.pickupPrice": "Pickup & Price",
        "order.pickupDate": "Pickup Date",
        "order.proposedPrice": "Proposed Price (₸)",
        "order.price": "Price",
        "order.postOrder": "Post Order",
        "order.posted": "Order Posted",
        "order.postedMessage": "Drivers can now see your order.",
        "order.fillCorrectly": "Please fill in all fields correctly",
        "order.cargo": "Cargo",
        "order.pickup": "Pickup",
        "order.status": "Status",
        "order.current": "Current",
        "order.accept": "Accept Order",
        "order.markAs": "Mark as",
        "order.details": "Order Details",
        "order.noOrders": "No orders yet",
        "order.tapNew": "Tap 'New Order' to post your first cargo.",
        "order.noAvailable": "No available orders",
        "order.checkLater": "Check back later.",
        "order.noActiveJobs": "No active jobs",
        "order.acceptHint": "Accept an order from the Available tab.",
        
        "order.length": "Length (cm)",
        "order.width": "Width (cm)",
        "order.height": "Height (cm)",
        "order.dimensions": "Dimensions",
        "order.sameCityError": "Pickup and destination cities must be different.",
        
        // Profile
        "profile.account": "Account",
        "profile.name": "Name",
        "profile.email": "Email",
        "profile.phoneLabel": "Phone",
        "profile.roleLabel": "Role",
        "profile.editProfile": "Edit Profile",
        "profile.logOut": "Log Out",
        "profile.editTitle": "Edit Profile",
        "profile.changeAvatar": "Change Avatar",
        "profile.changePassword": "Change Password",
        "profile.newPasswordHint": "New password (leave empty to keep)",
        "profile.saveChanges": "Save Changes",
        "profile.nameEmptyError": "Name and phone can't be empty.",
        "profile.settings": "Settings",
        "profile.appearance": "Appearance",
        "profile.language": "Language",
        
        // Appearance
        "appearance.system": "System",
        "appearance.light": "Light",
        "appearance.dark": "Dark",
        
        // Avatar picker
        "avatar.title": "Choose Avatar",
        "avatar.color": "Color",
        "avatar.icon": "Icon",
        "avatar.done": "Done",
        
        // Admin
        "admin.allUsers": "All Users",
        "admin.allOrders": "All Orders",
        "admin.editUser": "Edit User",
        "admin.editOrder": "Edit Order",
        "admin.info": "Info",
        "admin.assignment": "Assignment",
        "admin.customer": "Customer",
        "admin.driverEmail": "Driver email (or empty)",
        "admin.deleteUser": "Delete User",
        "admin.deleteOrder": "Delete Order",
        "admin.confirmDeleteUser": "Delete this user?",
        "admin.confirmDeleteOrder": "Delete this order?",
        "admin.cannotUndone": "This action cannot be undone.",
        "admin.cannotDelete": "Cannot Delete",
        "admin.cannotSave": "Cannot Save",
        "admin.cantDeleteSelf": "You can't delete your own account while logged in.",
        "admin.cantDeleteLastAdmin": "Can't delete the last admin account.",
        "admin.cantChangeOwnRole": "You can't change your own role while logged in as admin.",
        "admin.cantChangeLastAdminRole": "Can't change role — this is the last admin account.",
        "admin.promoteTitle": "Promote to Admin?",
        "admin.promoteMessage": "%@ will gain full admin access — they'll be able to view, edit, and delete all users and orders. Only another admin can revoke this role afterward. Are you sure?",
        "admin.promote": "Promote",
        "admin.cancel": "Cancel",
        "admin.ok": "OK",
        "admin.delete": "Delete",
        "admin.noOrdersAdmin": "No orders",
        "admin.ordersAppear": "Orders created by users will appear here.",
        
        // Statuses
        "status.pending": "Pending",
        "status.accepted": "Accepted",
        "status.inTransit": "In Transit",
        "status.delivered": "Delivered",
        
        // Cargo types
        "cargo.general": "General",
        "cargo.fragile": "Fragile",
        "cargo.refrigerated": "Refrigerated",
        "cargo.heavy": "Heavy",
        "cargo.furniture": "Furniture",
        
        // Roles
        "role.customer": "Customer",
        "role.driver": "Driver",
        "role.admin": "Admin",
        
        // Cities
        "city.almaty": "Almaty",
        "city.astana": "Astana",
        "city.shymkent": "Shymkent",
        "city.karaganda": "Karaganda",
        "city.aktobe": "Aktobe",
        "city.taraz": "Taraz",
        "city.pavlodar": "Pavlodar",
        "city.ustkamenogorsk": "Ust-Kamenogorsk",
        "city.semey": "Semey",
        "city.atyrau": "Atyrau",
        "city.kyzylorda": "Kyzylorda",
        "city.aktau": "Aktau"
    ]
    
    // MARK: - Russian
    static let ru: [String: String] = [
        "app.tagline": "Доставка грузов, упрощённая",
        
        "auth.email": "Эл. почта",
        "auth.password": "Пароль",
        "auth.login": "Войти",
        "auth.signup": "Регистрация",
        "auth.noAccount": "Нет аккаунта? Зарегистрируйтесь",
        "auth.invalidCredentials": "Неверная почта или пароль",
        "auth.fillAllFields": "Пожалуйста, заполните все поля",
        "auth.emailExists": "Аккаунт с такой почтой уже существует",
        "auth.createAccount": "Создать аккаунт",
        "auth.personalInfo": "Личные данные",
        "auth.fullName": "Полное имя",
        "auth.phone": "Телефон",
        "auth.iAmA": "Я являюсь",
        "auth.role": "Роль",
        
        "tab.myOrders": "Мои заказы",
        "tab.newOrder": "Новый заказ",
        "tab.profile": "Профиль",
        "tab.available": "Доступные",
        "tab.myJobs": "Мои работы",
        "tab.users": "Пользователи",
        "tab.orders": "Заказы",
        
        "order.route": "Маршрут",
        "order.from": "Откуда",
        "order.to": "Куда",
        "order.fromCity": "Откуда (город)",
        "order.toCity": "Куда (город)",
        "order.cargoDetails": "Детали груза",
        "order.type": "Тип",
        "order.weight": "Вес (кг)",
        "order.pickupPrice": "Дата и цена",
        "order.pickupDate": "Дата вывоза",
        "order.proposedPrice": "Предлагаемая цена (₸)",
        "order.price": "Цена",
        "order.postOrder": "Опубликовать заказ",
        "order.posted": "Заказ опубликован",
        "order.postedMessage": "Водители теперь видят ваш заказ.",
        "order.fillCorrectly": "Пожалуйста, заполните все поля корректно",
        "order.cargo": "Груз",
        "order.pickup": "Вывоз",
        "order.status": "Статус",
        "order.current": "Текущий",
        "order.accept": "Принять заказ",
        "order.markAs": "Отметить как",
        "order.details": "Детали заказа",
        "order.noOrders": "Заказов пока нет",
        "order.tapNew": "Нажмите 'Новый заказ', чтобы опубликовать груз.",
        "order.noAvailable": "Нет доступных заказов",
        "order.checkLater": "Загляните позже.",
        "order.noActiveJobs": "Нет активных работ",
        "order.acceptHint": "Примите заказ во вкладке 'Доступные'.",
        
        "order.length": "Длина (см)",
        "order.width": "Ширина (см)",
        "order.height": "Высота (см)",
        "order.dimensions": "Габариты",
        "order.sameCityError": "Города отправления и назначения должны быть разными.",
        
        "profile.account": "Аккаунт",
        "profile.name": "Имя",
        "profile.email": "Эл. почта",
        "profile.phoneLabel": "Телефон",
        "profile.roleLabel": "Роль",
        "profile.editProfile": "Редактировать профиль",
        "profile.logOut": "Выйти",
        "profile.editTitle": "Редактировать профиль",
        "profile.changeAvatar": "Сменить аватар",
        "profile.changePassword": "Сменить пароль",
        "profile.newPasswordHint": "Новый пароль (пусто — не менять)",
        "profile.saveChanges": "Сохранить",
        "profile.nameEmptyError": "Имя и телефон не могут быть пустыми.",
        "profile.settings": "Настройки",
        "profile.appearance": "Оформление",
        "profile.language": "Язык",
        
        "appearance.system": "Системное",
        "appearance.light": "Светлое",
        "appearance.dark": "Тёмное",
        
        "avatar.title": "Выбор аватара",
        "avatar.color": "Цвет",
        "avatar.icon": "Иконка",
        "avatar.done": "Готово",
        
        "admin.allUsers": "Все пользователи",
        "admin.allOrders": "Все заказы",
        "admin.editUser": "Редактировать пользователя",
        "admin.editOrder": "Редактировать заказ",
        "admin.info": "Информация",
        "admin.assignment": "Назначение",
        "admin.customer": "Клиент",
        "admin.driverEmail": "Эл. почта водителя (или пусто)",
        "admin.deleteUser": "Удалить пользователя",
        "admin.deleteOrder": "Удалить заказ",
        "admin.confirmDeleteUser": "Удалить этого пользователя?",
        "admin.confirmDeleteOrder": "Удалить этот заказ?",
        "admin.cannotUndone": "Это действие нельзя отменить.",
        "admin.cannotDelete": "Нельзя удалить",
        "admin.cannotSave": "Нельзя сохранить",
        "admin.cantDeleteSelf": "Нельзя удалить свой аккаунт во время сессии.",
        "admin.cantDeleteLastAdmin": "Нельзя удалить последнего администратора.",
        "admin.cantChangeOwnRole": "Нельзя сменить свою роль во время сессии администратора.",
        "admin.cantChangeLastAdminRole": "Нельзя сменить роль — это последний администратор.",
        "admin.promoteTitle": "Сделать администратором?",
        "admin.promoteMessage": "%@ получит полный доступ. Cможет просматривать, редактировать и удалять всех пользователей и заказы. Отозвать роль может только другой администратор. Вы уверены?",
        "admin.promote": "Назначить",
        "admin.cancel": "Отмена",
        "admin.ok": "ОК",
        "admin.delete": "Удалить",
        "admin.noOrdersAdmin": "Заказов нет",
        "admin.ordersAppear": "Здесь появятся заказы пользователей.",
        
        "status.pending": "Ожидает",
        "status.accepted": "Принят",
        "status.inTransit": "В пути",
        "status.delivered": "Доставлен",
        
        "cargo.general": "Обычный",
        "cargo.fragile": "Хрупкий",
        "cargo.refrigerated": "Охлаждаемый",
        "cargo.heavy": "Тяжёлый",
        "cargo.furniture": "Мебель",
        
        "role.customer": "Клиент",
        "role.driver": "Водитель",
        "role.admin": "Администратор",
        
        "city.almaty": "Алматы",
        "city.astana": "Астана",
        "city.shymkent": "Шымкент",
        "city.karaganda": "Караганда",
        "city.aktobe": "Актобе",
        "city.taraz": "Тараз",
        "city.pavlodar": "Павлодар",
        "city.ustkamenogorsk": "Усть-Каменогорск",
        "city.semey": "Семей",
        "city.atyrau": "Атырау",
        "city.kyzylorda": "Кызылорда",
        "city.aktau": "Актау"
    ]
}
